- name: create an address
  google.cloud.gcp_compute_address:
    name: address-instance
    region: "{{ region }}"
    project: "{{ gcp_project }}"
    auth_kind: "{{ gcp_cred_kind }}"
    service_account_file: "{{ gcp_cred_file }}"
    state: "{{ infra_state | default('present') }}"
  register: address