---
# - name: Unhold all packages
#   shell: apt-mark unhold $(apt-mark showhold)
#   ignore_errors: true

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  become_user: root
  become: yes

- name: Install prerequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: true

- name: Add Docker's official GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu jammy stable"
    state: present
  become: true

- name: Install Docker Engine
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  become: true

# - name: Install Docker
#   apt:
#     name: 
#       - docker.io
#       - docker-compose-plugin
#     state: present
#     update_cache: yes
#   become: true

- name: Start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true

# - name: Install Docker using official script
#   shell: |
#     curl -fsSL https://get.docker.com -o get-docker.sh
#     sh get-docker.sh
  # args:
  #   creates: /usr/bin/docker
  # become: true

# - name: Install Docker-related Packages
#   apt:
#     name: '{{ item }}'
#     state: present
#     update_cache: yes
#   loop:
#       - docker.io
#       - docker-compose
#   become_user: root
#   become: yes



- name: Ensure /opt/app directory exists
  file:
    path: /opt/app
    state: directory
    owner: root
    group: root
    mode: '0750'
  become: true
  tags: docker

- name: Docker Compose
  copy:
    src: templates/docker-compose.yml.j2
    dest: /opt/app/docker-compose.yml
    mode: '0640'
  become: true
  tags: docker


- name: Add user to docker group
  user:
    name: "{{ ansible_user }}"
    groups: docker
    append: yes
  become: true




- name: Copy application files
  copy:
    src: ../../app/
    dest: /opt/app/app/
    mode: '0640'
  become: true
  tags: docker

- name: Copy Dockerfile
  copy:
    src: ../../Dockerfile
    dest: /opt/app/Dockerfile
    mode: '0640'
  become: true
  tags: docker

- name: Copy Prometheus config
  copy:
    src: templates/prometheus/prometheus.yml
    dest: /opt/app/prometheus.yml
    mode: '0640'
  become: true

  tags: docker
- name: Copy Grafana provisioning files
  copy:
    src: templates/grafana/
    dest: /opt/app/grafana/
    mode: '0640'
  become: true
  tags: docker
  
# - name: Run docker-compose stack
#   community.docker.docker_compose_v2:
#     project_src: /opt/app
#     state: present
#   become: true
#   tags: docker

# - name: Build DockerImage
#   shell: dock

- name: Run Container
  shell: /usr/bin/docker compose -f /opt/app/docker-compose.yml up -d --build
  become: true
  tags: docker