---
# - name: Unhold all packages
#   shell: apt-mark unhold $(apt-mark showhold)
#   ignore_errors: true

- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
  become_user: root
  become: yes

# - name: Install Docker using official script
#   shell: |
#     curl -fsSL https://get.docker.com -o get-docker.sh
#     sh get-docker.sh
  # args:
  #   creates: /usr/bin/docker
  # become: true

- name: Install Docker-related Packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop:
      - docker.io
      - docker-compose
  become_user: root
  become: yes


- name: Ensure /opt/app directory exists
  file:
    path: /opt/app
    state: directory
    owner: root
    group: root
    mode: '0750'
  become: true

- name: Docker Compose
  copy:
    src: templates/docker-compose.yml.j2
    dest: /opt/app/docker-compose.yml
    mode: '0640'
  become: true

- name: Copy application files
  copy:
    src: ../../app/
    dest: /opt/app/app/
    mode: '0640'
  become: true

- name: Copy Dockerfile
  copy:
    src: ../../Dockerfile
    dest: /opt/app/Dockerfile
    mode: '0640'
  become: true

- name: Copy Prometheus config
  copy:
    src: templates/prometheus/prometheus.yml
    dest: /opt/app/prometheus.yml
    mode: '0640'
  become: true

- name: Copy Grafana provisioning files
  copy:
    src: templates/grafana/
    dest: /opt/app/grafana/
    mode: '0640'
  become: true
  
- name: Run docker-compose stack
  community.docker.docker_compose_v2:
    project_src: /opt/app
    state: present
  become: true


# - name: Build DockerImage
#   shell: dock

# - name: Run Container
#   shell: docker-compose -f /opt/app/docker-compose.yml up -d 