name: Deploy Fast API Application with Monitoring

on: workflow_dispatch
permissions:
  contents: read
  id-token: write

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v5

    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest pytest-asyncio httpx

    - name: Run tests
      run: |
        pytest app/tests/ -v

    - name: Sonar Scan
      uses: sonarsource/sonarcloud-github-action@master
      with:
        args: >
          -Dsonar.projectKey=muchconsulting-devops-demo
          -Dsonar.organization=rigamortus
          -Dsonar.host.url=https://sonarcloud.io
          -Dsonar.python.coverage.reportPaths=app/coverage.xml
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Install Ansible and dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ansible google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

    - name: Configure GCP credentials
      uses: google-github-actions/auth@v1
      with:
        token_format: 'access_token'
        workload_identity_provider: ${{ secrets.GCP_WIP }}
        service_account: ${{ secrets.GCP_SA_EMAIL }}

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        export_default_credentials: true

    - name: Run Ansible Playbook
      env:
        GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
        GCP_SERVICE_ACCOUNT_FILE: ${{ secrets.GCP_SA_FILE }}
      run: |
        ansible-playbook -i "localhost," -c local ansible/playbook.yml --extra-vars "gcp_project=${{ secrets.GCP_PROJECT }} gcp_cred_kind=serviceaccount gcp_cred_file=${{ secrets.GCP_SA_FILE }} region=us-central1 zone=us-central1-a infra_state=present docker_image=docker.io/davidkalugo/fastapi-demo:latest"
